services:
  - type: web
    name: wc-fever-2026-api
    runtime: python
    buildCommand: pip install -r api/requirements.txt
    startCommand: gunicorn --chdir backend app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
